name: ci
on:
  push: { branches: [ main, master ] }
  pull_request: {}
jobs:
  build-wsl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - name: Build WSL host
        run: nix build --print-build-logs .#nixosConfigurations.wsl.config.system.build.toplevel
